### ISSUE TITLE
Runs an unexpected script

### ISSUE THREAD

**Issue by sittim** [ntpeters/vim-airline-colornum#14]
I started this issue here:

https://github.com/SirVer/ultisnips/issues/620

When I use UltiSnips in markdown file, the vim-airline-colornum runs some unexpected script.  For example, when the vim-airline-colornum plugin is enabled, while working on markdown file, if I enter:

`sec<c-e>`

something blinks, the snippet editing ends and the following shows up

`# ge #`

When the vim-airline-colornum plubin is not enabled (Uninstalled), and I enter `sec<c-e>`, the following shows up with snippet editing still enabled as expected:

`# Section Name #`

This issues seems to only appear in markdown files.

My configs can be found here:

https://github.com/sittim/configs

**Comment by ntpeters** [comment]
As mentioned by @seletskiy in your original issue, it appears that this type of behavior is somehow being caused by vim-airline itself in some cases.
