### ISSUE TITLE
Trailing zero at the end of statusline

### ISSUE THREAD

**Issue by daveyarwood** [ntpeters/vim-airline-colornum#15]
See: https://github.com/vim-airline/vim-airline/issues/1164

I initially thought this was an airline issue, but `:verbose :fu UpdateCursorLineNr` shows that this function is defined in `~/.vim/bundle/vim-airline-colornum/plugin/airline-colornum.vim`

From the source of the function, it does look like the issue is that this function returns 0 instead of `''`, although I'm confused about what this function does and why it is being called at the end of my statusline.

**Comment by ntpeters** [comment]
Hey, nice catch! Can't believe I never noticed that before... Should be fixed now.

This function is what actually performs the update of the cursor line number color. I inject it into the statusline because then I can guarantee that the color is updated whenever vim-airline updates its color.

**Comment by daveyarwood** [comment]
Gotcha, that makes sense. I updated and problem solved. Thanks for the quick fix! 👍
