### ISSUE TITLE
UpdateCursorLineNr() breaks Visual Block

### ISSUE THREAD

**Issue by pi-rho** [ntpeters/vim-airline-colornum#7]
The feedkeys() call in this function makes Ctrl-V visual blocks work strangely. If the cursor is in the first column and I hit Ctrl-V, suddenly, there's a visual block that covers the current line and the previous line with the width of the previous line.  Changing the feedkeys call from `<left><right>` to `<right><left>` cures the symptom.
a diff off of master:

``` diff
diff --git a/plugin/airline-colornum.vim b/plugin/airline-colornum.vim
index 13cc607..b013b85 100644
--- a/plugin/airline-colornum.vim
+++ b/plugin/airline-colornum.vim
@@ -137,7 +137,7 @@ function! UpdateCursorLineNr()

                 " Cause the cursor line num to be redrawn to update color
                 if <SID>ShouldRedrawCursorLineNr()
-                    call feedkeys("\<left>\<right>", 'n')
+                    call feedkeys("\<right>\<left>", 'n')
                 endif

                 " Save last mode
```

**Comment by ntpeters** [comment]
I'm unable to reproduce this, but there also doesn't seem to be any harm in reversing the key order here.  It's fixed.

**Comment by pi-rho** [comment]
Sorry -- line 140 needs the change.

Steps to reproduce:
- open plugin/airline-colornum.vim
  ![selection_123](https://cloud.githubusercontent.com/assets/1191081/9705350/6cfb90f8-5487-11e5-8c44-4b418048c9cd.png)
- Type:
  - `140G0<Ctrl-V>`
    ![selection_124](https://cloud.githubusercontent.com/assets/1191081/9705352/75c8cb24-5487-11e5-8163-c60f912022f2.png)
- any time the cursor is in the first column, when you go into Visual Block mode, the cursor moves and selects a region
