### ISSUE TITLE
Breaks some visual mode operations

### ISSUE THREAD

**Issue by craigp** [ntpeters/vim-airline-colornum#8]
When I have this plugin enabled things like `vib` stop working properly, inserting a `b` instead of selecting the text region inside the brackets.

**Comment by ntpeters** [comment]
Hmm, that's odd.  `vib` seems to work fine for me with this enabled.  Could you possibly try disabling plugins other than this one to see if something is interacting strangely with it?  Could you also provide the output of `vim --version`?

**Comment by sielicki** [comment]
I can confirm this issue, though I'm on neovim and you should confirm yourself.

The prior [issue](https://github.com/ntpeters/vim-airline-colornum/issues/7) didn't elaborate well on how to reproduce it. The following method has been reproducible for me every time:
- Start with some text that has no whitespace in front of it.
  eg: 
  The quick brown fox
  Jumps over the lazy
  dog.
- With your cursor on the first line: `:0`, move to the beginning of the line: `^`
- Start a visual block: `<C-v>`
- Move your cursor down a couple lines: `2j`, 
- Insert block insert mode, `I` (that's a capital I), type some text, and hit `ESC`.

This addition should have been at the beginning of the line, but it's after the first character instead.

What's going on is that the order of the keys in the feedkeys call, `call feedkeys("\<left>\<right>", 'n')`, isn't actually neutral if you're at the beginning of the line or end of line.

I can confirm [this](https://github.com/ntpeters/vim-airline-colornum/pull/10) fixes it. Please merge.

**Comment by liuyang1** [comment]
also have this problem. @sielickin seems right, help merge it.

**Comment by ntpeters** [comment]
Fixed in #10
